TOOLS-1555 sdcnode v4 builds for the gz Reviewed by: Robert Mustacchi <rm@joyent.com> Reviewed by: Julien Gilli <julien.gilli@joyent.com> Approved by: Julien Gilli <julien.gilli@joyent.com>

diff --git a/tools/build-a-node b/tools/build-a-node
--- a/tools/build-a-node
+++ b/tools/build-a-node
@@ -25,8 +25,15 @@
 # - version:
 # - sha: Optional. If given it overrides `version` for the 'git checkout'.
 # - configure_flags:
-# - build_env:
+# - build_env: Environment vars to pass to the `make` command to build node
 # - build_tag:
+# - gcc_version_range: A node-semver range to compare against the GCC used to
+#   build node
+# - rpath: A string to which to set the node RPATH/RUNPATH.
+# - include_gcc_runtime_libs: Include the needed libs from the GCC runtime
+#   (/opt/local/lib/gcc$major$minor/...) that are used by the built node.
+#   Commonly this is used together with `rpath=$ORIGIN/../lib` to make node
+#   able to load those libs.
 # - patch_files: Optional. A list of paths (relative to the project root)
 #   of patch files to apply.
 # - npm_version: Optional. A commitish for a special version of npm to pull in
@@ -42,6 +49,11 @@ set -o errexit
 set -o pipefail
 
 TOP=$(cd $(dirname $0)/../ >/dev/null; pwd)
+
+GCC=/opt/local/bin/gcc
+GXX=/opt/local/bin/g++
+ELFEDIT=/usr/bin/elfedit
+
 buildOpts=$1
 buildDir=$2
 buildStamp=$3
@@ -49,6 +61,18 @@ buildStamp=$3
 echo ""
 echo "# Build a node in $buildDir with this config:"
 echo "$buildOpts" | json
+
+# Ensure we have a particular gcc version.
+gccVersionRange=$(echo "$buildOpts" | json gcc_version_range)
+if [[ -n "$gccVersionRange" ]]; then
+    currGccVer=$($GCC --version | head -1 | awk '{print $NF}')
+    matching=$(./node_modules/.bin/semver -r "$gccVersionRange" $currGccVer || true)
+    if [[ -z "$matching" ]]; then
+        echo "build-a-node: fatal error: gcc version ($currGccVer) does not" \
+            "match the given range: $gccVersionRange" >&2
+        exit 1
+    fi
+fi
 
 if [[ -d $buildDir ]]; then
     rm -rf $buildDir
@@ -95,11 +119,32 @@ configureFlags=$(echo "$buildOpts" | json configure_flags)
 if [[ -z "$configureFlags" ]]; then
     configureFlags="--with-dtrace"
 fi
-buildEnv=$(echo "$buildOpts" | json build_env)
-eval "export $buildEnv"
 ./configure $configureFlags --prefix=$buildDir/node
-make V=1 CC=/opt/local/bin/gcc CXX=/opt/local/bin/g++
-make V=1 CC=/opt/local/bin/gcc CXX=/opt/local/bin/g++ install
+
+buildEnv=$(echo "$buildOpts" | json build_env)
+make V=1 CC=$GCC CXX=$GXX $buildEnv
+make V=1 CC=$GCC CXX=$GXX $buildEnv install
+
+# Optionally include GCC runtime libs. If a version of GCC was used to compile
+# node is greater than the version of the GCC runtime libs included in the
+# platform *and* this node build is targetted for use in the GZ, then the
+# node build needs to (a) include the needed GCC runtime libs and (b) set a
+# RUNPATH for the node binary to find them.
+#
+# See <https://github.com/joyent/rfd/tree/master/rfd/0059#problems-with-the-gz>
+# for details.
+includeGccRuntimeLibs=$(echo "$buildOpts" | json include_gcc_runtime_libs)
+if [[ -n "$includeGccRuntimeLibs" ]]; then
+    ldd ./node  | awk '{print $3}' | grep '^/opt/local/gcc' | while read lib; do
+        cp $lib $buildDir/node/lib/
+    done
+fi
+
+rpath=$(echo "$buildOpts" | json rpath)
+if [[ -n "$rpath" ]]; then
+    $ELFEDIT -e "dyn:runpath $rpath" $buildDir/node/bin/node
+fi
+
 
 # trim
 rm -rf $buildDir/node/lib/node_modules/npm/.git
