TOOLS-883: sdcnode v0.10.37 (at untagged sha f2a45ca)
+b4bdc598-8939-11e3-bea4-8341f6861379-v0.10.37-zone
+b4bdc598-8939-11e3-bea4-8341f6861379-v0.10.37-zone64
+fd2cc906-8938-11e3-beab-4359c665ac99-v0.10.37-zone
+fd2cc906-8938-11e3-beab-4359c665ac99-v0.10.37-gz
+de411e86-548d-11e4-a4b7-3bb60478632a-v0.10.37-zone

diff --git a/tools/build-a-node b/tools/build-a-node
--- a/tools/build-a-node
+++ b/tools/build-a-node
@@ -23,6 +23,7 @@
 #
 # TODO: document supported build options
 # - version:
+# - sha: Optional. If given it overrides `version` for the 'git checkout'.
 # - configure_flags:
 # - build_env:
 # - build_tag:
@@ -57,7 +58,16 @@ mkdir -p $buildDir
 cp -PR $TOP/build/src $buildDir/src
 cd $buildDir/src
 version=$(echo "$buildOpts" | json version)
-git checkout $version
+if [[ -z "$version" ]]; then
+    echo "build-a-node: fatal error: no 'version' given" >&2
+    exit 1
+fi
+sha=$(echo "$buildOpts" | json sha)
+if [[ -n "$sha" ]]; then
+    git checkout $sha
+else
+    git checkout $version
+fi
 
 npmVersion=$(echo "$buildOpts" | json npm_version)
 if [[ -n "$npmVersion" ]]; then
